server: 
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
  tomcat:
    connection-timeout: ${SERVER_CONNECTION_TIMEOUT:-1}
    
logging:
  level:
    '[org.springframework.security]': ${LOG_LEVEL:INFO}
    '[org.springframework.data.mongodb.core.MongoTemplate]': ${LOG_LEVEL:INFO}
    '[org.springframework.web.client.RestTemplate]': ${LOG_LEVEL:DEBUG}
    '[org.quartz.core]': ${QUARTZ_LOG_LEVEL:ERROR}
    '[org.springframework.web.socket.config.WebSocketMessageBrokerStats]': ${SOCKET_LOG_LEVEL:ERROR}
      
spring:
  servlet:
    multipart:
      max-file-size: ${EVITA_MAX_FILE_SIZE:20MB}
      max-request-size: ${EVITA_MAX_FILE_SIZE:20MB}
      enabled: true
  devtools:
      add-properties: false
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE_NAME:idra-plugin-manager}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:pssw}
      authentication-database: ${MONGO_AUTHENTICATION_DB:admin}
      auto-index-creation: true

mongodb:
  encrypt: 
    key1: ${MONGODB_ENCRYPT_KEY1:hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=}
    key2: ${MONGODB_ENCRYPT_KEY2:cUzurmCcL+K252XDJhhWI/A/+wxYXLgIm678bwsE2QM=}
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html 

idra:
  basepath: ${IDRA_BASEPATH:http://localhost:8080}
  
